name: Build

on:
  merge_group:
  pull_request:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_regular:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: install prerequisites
        run: sudo apt-get update && sudo apt-get install -y meson ninja-build
      - name: build
        run: meson setup build && ninja -C build
      - name: test
        run: ./build/memtouch --help

  check-clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: install prerequisites
        run: sudo apt-get update && sudo apt-get install -y meson ninja-build clang-format
      - name: check
        run: meson setup build && ninja -C build clang-format-check

  build_nix_shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: cachix/install-nix-action@v30
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: build
        run: nix develop -i --command bash -c "meson setup build && ninja -C build"
      - name: test
        run: nix develop -i --command bash -c "./build/memtouch --help"

  build_nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: nix build
        run: nix build .
      - name: nix test
        run: nix run . -- --help
